{% if clam_include %}
include: "{{clam_include}}"
{% endif %}
port: 8805
urlprefix: "alpino"
root: "{{www_data_path}}/alpino.clam/"
bindir: "{{lm_prefix}}/bin/"
oauth_client_url: "{{lm_base_url}}/alpino"
{% if "switchboard" in remote_services and remote_services.switchboard %}
switchboard_forward_url: "{{remote_services.switchboard}}/#/alpino/$BACKLINK/$MIMETYPE/nld"
{% endif %}
{% if "frog" in remote_services and remote_services.frog %}
frog_forward_url: "{{remote_services.frog}}/?project=new&foliainput_url=$BACKLINK&skip=t"
{% elif webserver and ("all" in services or "frog" in services)  %}
frog_forward_url: "{{lm_base_url}}/frog/?project=new&foliainput_url=$BACKLINK&skip=t"
{% endif %}
