---
  - name: Installing global dependencies for Deepfrog
    include_role:
      name: lamachine-package-install
    with_items:
      - { debian: libssl-dev, redhat: openssl-dev, arch: openssl } #should already be installed earlier but no harm in making it explicit here anyway
    loop_control:
      loop_var: package

  - name: Installing libtorch on macOS
    homebrew:
      name: [ libtorch ]
      state: present
    when: ansible_distribution|lower == 'macosx'

  - name: Downloading libtorch for linux
    get_url:
        url: https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.8.1%2Bcpu.zip
        dest: "{{ lm_prefix }}/opt/libtorch.zip"
    when: ansible_distribution|lower != 'macosx'

  - name: Unpacking libtorch for linux
    shell: "unzip -o libtorch.zip"
    args:
      chdir: "{{ lm_prefix }}/opt"
    when: ansible_distribution|lower != 'macosx'

  - name: "Adding activation script for libtorch"
    become: "{{lm_become}}"
    become_user: root
    copy:
      dest: "{{lm_prefix}}/bin/activate.d/libtorch.sh"
      content: |
        export LIBTORCH={{lm_prefix}}/opt/libtorch
        export LD_LIBRARY_PATH=$LIBTORCH/lib:$LD_LIBRARY_PATH
      mode: u+rwx,a+rx
    when: ansible_distribution|lower != 'macosx'

  - name: "Installing DeepFrog"
    shell: |
       if [ -e "{{lm_prefix}}/opt/libtorch" ]; then
         export LIBTORCH={{lm_prefix}}/opt/libtorch
         export LD_LIBRARY_PATH=$LIBTORCH/lib:$LD_LIBRARY_PATH
       fi
       cargo install deepfrog
    environment: "{{lm_env}}"
