{% if clam_include %}
include: "{{clam_include}}"
{% endif %}
port: 8806
urlprefix: "piccl"
root: "{{www_data_path}}/piccl.clam/"
piccldir: "{{lm_prefix}}/opt/PICCL"
piccldataroot: "{{lm_prefix}}/opt/PICCL"
oauth_client_url: "{{lm_base_url}}/piccl"
{% if "autosearch" in remote_services and remote_services.autosearch %}
autosearch_forward_url: "{{ remote_services.autosearch}}/upload/?format=piccl&file=$BACKLINK"
{% endif %}
{% if "switchboard" in remote_services and remote_services.switchboard %}
switchboard_forward_url: "{{ remote_services.switchboard }}/#/piccl/$BACKLINK/$MIMETYPE"
{% endif %}
