{% if clam_include %}
include: "{{clam_include}}"
{% endif %}
port: 8821
urlprefix: "asr4J"
root: "{{www_data_path}}/asr4J.clam/"
bindir: "{{lm_prefix}}/bin/"
oauth_client_url: "{{lm_base_url}}/asr4J"
